### PR TITLE
Enable INFO level logging for keripy witnesses

### PR DESCRIPTION
**Pull request by rubelhassan**
keripy INFO level logs cover most of the cases.

hio.help.ogling module provides Ogler class for global logging in keripy. The class can print log to

- console
- syslog
- file

### CODE REVIEW

**Comment by rubelhassan** [comment]
@dhh1128 @Arsh-Sandhu @s-a-tanjim I've enabled INFO level logging for Keripy which logs most of the cases of witness interactions. Please suggest any important events you think are necessary to log, and I'll add logs for them.

**Comment by rubelhassan** [comment]
As discussed with Shoeb console base logging is sufficient for now.

**Review by dhh1128 — APPROVED** [review]
LGTM

**Comment by s-a-tanjim** [comment]
@rubelhassan  I made small changes on top of your work. Can you please review it: https://github.com/provenant-dev/keripy/pull/3

**Review by dhh1128 — APPROVED** [review]

**Pull request merged**
